apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 1m0s
  # dependsOn:
  # - name: infra-configs
  retryInterval: 1m 
  timeout: 5m 
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./services/plex/overlays/staging
  prune: true
