apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:/ANm4k2snPgG+HIVGwfjx2o3PIQaoC176ldelnucuxefAxd1T0iyT9WRW4IlpwHprSRuL/riM8vOeA3jbQrR+XZBXxEtDbZC+jiQ786hKv8oRIcr2aKInK33avHkIBrksafOIj8afKwtJlpz6mzEQDH7PNZ4HY1XHjQ3e8Vons8W2kxdeEdrMkgUgTM1Q9cT4LWSSk+Ky8fxgMf59z8erW7bdjhSmpxo7LW1f2xRbanJX5mrLfb8BdUG2wGqxvniFbJPAlayuJ9foFzxHVpkH9qjeMVwTIwEglfgiqNIckA1/jke7th2zPaVKiniUYza,iv:V9teLB5yFM+JRGVl+d6122OMIntqxwlxhr9ebGCw5ok=,tag:jf7twXk5mJg/xTbTVZkDUQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflared-secret
    namespace: cloudflared
sops:
    age:
        - recipient: age1y6h6gh3memsng0n3465xunvrzd0des7fkkkjycsf7y8leqg5dspssa63fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVXVvTXA3UVR0aFQwcnZS
            NUtKMGw0YXkxUUxYcFBiaU5UeDFjNlM0cmdzCnI1YTQ4aEpweG0xUnlzU2gvMHFr
            UkVXTUVKZm54bXUyRUl5cEEvZ0xNdUUKLS0tIHVvL0x1Z3dDcWNqSlNBTXBQcnRs
            SW5iUjhjbUR1bER2QmVCQnFNMi80MkUKphlIBz9NrdrAD+m+W7wwb6DqKlezEJMX
            K6hEHTOGgv3/CPz7W06PRolue/ZO8mhk/jZKtuIrXVABuyWS1am0iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T02:47:21Z"
    mac: ENC[AES256_GCM,data:BIQOyxNcxdvFwnHwIISGT4Yl1IDyhxmZ+6hNQllMr99k9A0AAbSHY82sGkbbKn/TI3lH6a63CCkTFbHlcZOzlXvQfy/Tq3hN74JXXAFB4EmDWEv3RtR1JjvVwa4+0J4RikBkXMbv0zfTHh5EVXKTbndxjSNAWdgJriF1Zs28gy4=,iv:Qugu7Qt6qBxcVbKCgMMihRkzSCpN4Wkf9ZZNlmvqbdM=,tag:UNxHCdwTkiJCz893T6ELzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
